virt-who/virt-who

rel-eng/releasers.conf
rel-eng/tito.props

This PR sets everything up for use with the tito build/release tool, available in Fedora and EPEL. 
Before it can be used, once merged, you'll need to create an initial tag, presumably the 0.13 release. Just run (tito tag, and accept or modify the changelog message as you see fit)  The spec file will be adjusted automatically for you and included with the commit tag. Tag format will become "virt-who-0.13-1" (version and release included)
For all future tags, the changelog will actually be auto-generated for you.
If you prefix first line of commit messages with "BUGZILLANUMBER: Message", it will auto-generate dist-git commit messages, as well as do some bugzilla flag checking, and optionally use a placeholder "rebase" bug if no flagged commits are found. Very helpful for RHEL building. …

Initialize for tito usage

---

README
virt-who.8
virt-who.conf
virtwho.py

Added named options to config and cli for satellite 5 and 6.
satellite 6 maps to sam.
satellite 5 maps to satellite.
satellite remains a cli option but is not advertised.

1118064: Update options for Satellite naming

---

config.py
tests/test_esx.py
tests/test_libvirtd.py
tests/test_virtwho.py
virt-who.conf
virt/esx/esx.py
virt/libvirtd/libvirtd.py
virt/virt.py
virtwho.py

This modifies when virt-who sends reports to the following times:
- On start up: As soon as virt-who is started up, all virt backends will make an initial report which virt-who will send
- On reload: Reload causes the virt backends to be restarted, now it also clears the list of sent reports (so as to ignore any changes or lack there of)
- On receipt of a report different from the last one generated by the same virt backend: Virt-who now keeps track of the hash of the last report sent for each configured virt backend.
- In oneshot mode: No changes are tracked between runs in oneshot mode
The minimum interval to collect / send reports has been raised to 10 minutes.
Changes to the virt backends are as follows:
-libvirtd: All reports, aside from an initial report created when the process …

Change Detection

---

util.py
virt/fakevirt/fakevirt.py

The _decode function located inside fakevirt can be useful for general json decoding. As such I believe it should be moved to the util module.

Moves fakevirt._decode() to util.decode()

---

log.py
tests/test_log.py

Some of the tests (involving FileHandlers) were trying to open various files on the file system.
This patch mocks out logging.FileHandler._open for those tests which should prevent any files from actually being opened.

Patch logging.FileHandler._open to prevent any actual file access

---

virt/esx/esx.py
virt/fakevirt/fakevirt.py
virt/hyperv/hyperv.py
virt/libvirtd/libvirtd.py
virt/virt.py

This adds a new field to the virt guest model, hypervisorVersion. This new field is populated with the version information of the hypervisor software running on the host.
The version information is retrieved per hypervisor (in case virt-who was configured to connect to a vCenter instance etc).
The version number included is the version of the vmms.exe on the file system. According to (1) (and many others that I found like it), it seems this version number is the authoritative one with regards to hyperv.
The version info, as well as the hypervisorType, is supplied via a method of libvirt. The version number returned is of the following form:
`version_number = 1000000 * major_version + 1000 * minor_version + release`
At this time the version of kvm running on the host machines, while known …

Adds hypervisor version information to guests (ESX, hyperv, libvirt)

---

virt-who.spec
virt/esx/esx.py

This reports the hostname of each ESX instance by gathering the HostSystem.config.network.dnsConfig.hostName and HostSystem.config.network.dnsConfig.domainName.
This also includes a change to the spec file adding /etc/virt-who.conf to the expected files.

Fix for hostname detection in ESX

---

virt-who-config.5
virtwho/config.py
virtwho/virt/virt.py

I have a customer with a single vcentre infrastructure manageing a large number of esx servers. They restrict the guests by esx to linux on hosts names esxlin*, windows on esxwin* and vdi on esxvdi.  Because of this their exclude_hosts list is now approximately 40 hosts long, which is unmanageable. 
This patch introduces a new config directive exclude_hosts_regex that acts exactly like exclude_hosts but instead takes comma separated list of (python) regular expression to allow users to filter automatically in a neater and more manageable fashion. i.e. exclude_hosts_regex="esxwin.*","esxvdi.*"

Add config directives to allow filtering hosts according to regex not just string matches

---

virtwho/password/__main__.py

virt-who-password currently reads input only interactively via getpass
which prevents it from being used in scripts.
This patch adds fixes the issue by adding options -p and --password.

Adds --password option to virt-who-pasword

---

tests/test_esx.py
tests/test_hyperv.py
tests/test_log.py
tests/test_rhevm.py
tests/test_virtwho.py
tests/test_xen.py
virtwho/executor.py
virtwho/log.py
virtwho/main.py
virtwho/virt/virt.py

This is step 1 of the interval design.
As virt-who does not need to take advantage of multiple physical cores,
we have decided to move from using processes to threads.
We consider it more maintainable and reliable to get threads to stop
than processes.
Update tests to use threading where necessary
Fix patching to refer to the right Queue class
Update assertions to ensure the proper termination method is called

Move from using processes to threads

---

tests/test_datastore.py
virtwho/datastore.py

This is the implementation of step 2 of the interval design.
This step depends on all prior steps.
This PR adds a threadsafe datastore into the virt-who codebase. The datastore (as of this PR) is not in use in virt-who, it is to be used in subsequent steps of the design. More specifically, this datastore will be used to allow "destination" threads to consume reports produced by one or more "source" threads.
Related trello card: https://trello.com/c/HvuaQygd/275-interval-design-step-2-create-datastore
Design doc for the overall design: https://docs.google.com/document/d/1AV-eEp1HeemTHIiigGsUBDFK3W1XWMC1flSt9jrxek4/edit

Step 2 of the interval design: Implement a threadsafe datastore

---

tests/test_config.py
virtwho/config.py
virtwho/virt/virt.py

This is step 3 of the interval design. The configuration is now
parsed into unique destinations and sources. Historical Config
objects are treated as sources and the destination information
is pulled out of them and tracked. In this way the main thread
will know how many destination/source threads (and of what type) to
start.

Update ConfigManager to produce destination and source mappings.

---

tests/test_esx.py
tests/test_fake.py
tests/test_hyperv.py
tests/test_libvirtd.py
tests/test_rhevm.py
tests/test_vdsm.py
tests/test_virt.py
tests/test_virtwho.py
tests/test_xen.py
virtwho/executor.py
virtwho/virt/__init__.py
virtwho/virt/esx/esx.py
virtwho/virt/fakevirt/fakevirt.py
virtwho/virt/hyperv/hyperv.py
virtwho/virt/libvirtd/libvirtd.py
virtwho/virt/rhevm/rhevm.py
virtwho/virt/vdsm/vdsm.py
virtwho/virt/virt.py
virtwho/virt/xen/xen.py

This PR changes a number of things. Firstly common functionality between the Virt class (and subclasses) and what would be the Destination Thread class has been pulled out and put into a new super class for both IntervalThread. Secondly, I have implemented a DestinationThread class that should be able to use any existing manager to send reports gathered from the datastore (by name) to the right endpoints. Thirdly, tests have been added for the new DestinationThread (and updated for the Virt subclasses).
With any luck, this will be the second to last PR before the interval design will be functional.

Implement the Destination Thread and friends

---

tests/complex/virtwhotest.py
tests/test_config.py
tests/test_esx.py
tests/test_libvirtd.py
tests/test_virt.py
tests/test_virt_intervalthread.py
tests/test_virtwho.py
virtwho/config.py
virtwho/executor.py
virtwho/main.py
virtwho/manager/manager.py
virtwho/manager/subscriptionmanager/subscriptionmanager.py
virtwho/virt/__init__.py
virtwho/virt/esx/esx.py
virtwho/virt/libvirtd/libvirtd.py
virtwho/virt/virt.py
virtwho/virt/xen/xen.py

This PR modifies and utilizes the other building blocks from the other interval_* PRs to actually start using destination threads as per the design.
Note that this branch represents the minimum viable implementation (from my perspective) of the interval design and that much of what is contained herein will be changed in future work on virt-who configuration.
The ways to test this are numerous. I would suggest running this branch from source with different test configurations and options as you normally would with virt-who prior to the interval design and looking for any difference in functionality. The primary expected difference is that virt-who will now send all reports on the interval for each owner/env (for satellite 6 / hosted) and each configured satellite 5 instance per interval. …

Bring it all together with interval threads!

---

tests/complex/virtwhotest.py
tests/test_config.py
tests/test_datastore.py
tests/test_esx.py
tests/test_fake.py
tests/test_hyperv.py
tests/test_libvirtd.py
tests/test_log.py
tests/test_rhevm.py
tests/test_vdsm.py
tests/test_virt.py
tests/test_virt_intervalthread.py
tests/test_virtwho.py
tests/test_xen.py
virtwho/config.py
virtwho/datastore.py
virtwho/executor.py
virtwho/log.py
virtwho/main.py
virtwho/manager/manager.py
virtwho/manager/subscriptionmanager/subscriptionmanager.py
virtwho/virt/__init__.py
virtwho/virt/esx/esx.py
virtwho/virt/fakevirt/fakevirt.py
virtwho/virt/hyperv/hyperv.py
virtwho/virt/libvirtd/libvirtd.py
virtwho/virt/rhevm/rhevm.py
virtwho/virt/vdsm/vdsm.py
virtwho/virt/virt.py
virtwho/virt/xen/xen.py

This set of changes allows virt-who to send all reports (batched where possible) on the interval for each destination. Reports for different destinations no longer block each other and cause check in times to increase. This allows virt-who to be set up more effectively for large organizations having some set of hypervisors that need to be reported to more than one organization or environment or even more than one satellite!

1436811: Send reports on the interval per destination

---

virtwho/config.py

Let's say you have one configuration in /etc/virt-who.d/ named 'test.conf'
Given the above, running 'virt-who -o -d --config /etc/virt-who.d/test.conf' will cause virt-who to start, collect reports, and fail to send anything to the server.
This should not be the case. Even made to read the same config twice there should not be a lack of communication with the end destination. This PR fixes that by changing the set operation done on update of the dest_to_source map.
Please note: When you try the above you will likely notice that there are two source threads started, each for the same actual source of information. This is not necessary and should likely be fixed. It is not fixed here as it is historical behaviour.

1439317: Ensure reports are still sent despite duplicate configurations

---

virtwho/executor.py
virtwho/virt/fakevirt/fakevirt.py

These are some bits that needed a bit of love post interval design.
The fake virt backend already had a method _get_data that was overriding the new super classes version of the method.
We certain threads fail to run properly in oneshot mode, it was possible to fail with a runtime exeception (and stall the process). This was due to an attempt to join a thread not started. This PR fixes that. In future builds, please add this as part of the RFE for the interval bits.

Do not join threads not started, fix up fake backend

---

tests/test_virt.py
virtwho/manager/subscriptionmanager/subscriptionmanager.py
virtwho/virt/esx/esx.py
virtwho/virt/virt.py

To restore some historical behaviour that was lost during the implementation of the interval design, this PR causes virt-who to send all known reports as soon as it has received something from each source on the initial run.
With out this PR you must wait one interval before virt-who sends anything.

1442337: Send updates immediately the first run

---

virt-who-config.5
virtwho/config.py
virtwho/main.py

These updates are related to the implementation of the RFE bug 1369107.
Herein are changes to the documentation as well as one of the log messages to help communicate the new requirement for config files to end in '.conf'.

1369107: Update docs and log message to show the *.conf requirement

---

virtwho/config.py

Seemed like a quick fix to the referenced bug.
Basically, if we fail to decrypt the password for a config, log it and continue (if there are other configs left to run with).

1447264: Keep running on InvalidPasswordFormat given other valid configs

---

virtwho/virt/virt.py

The behaviour of virt-who prior to the implementation of the interval design, was to continue running despite connection failures when attempting to send reports.
This PR applies the same behaviour to the new design.
When reviewing this PR, in order to see the difference in behaviour for yourself, please follow the reproduction steps in the bug https://bugzilla.redhat.com/show_bug.cgi?id=1450747

1450747: Continue running destination threads on internal failure

---

tests/test_virt.py
virtwho/virt/virt.py

This PR fixes the behaviour of polling when in oneshot mode, when CTRL-C is pressed, and when a http 429 response is received.
In oneshot mode, virt-who will make one attempt to report on each source at most. If any exception occurs during communication (including http 429), virt-who will move on. This is restoring the historical behaviour of virt-who oneshot mode.
When CTRL-C is pressed (to kill the virt-who process) virt-who now exits without polling or making additional connections. Prior to this PR, virt-who would start polling as fast as it could until it was successful.
When an http 429 is received virt-who will check for the existence of a Retry-After header. If provided and more than the minimumSendInterval (currently 60s) then that value will be used as the wait time until the …

1448267: Fix polling behavior for oneshot, CTRL-C, 429 responses

---

tests/test_rhevm.py
virtwho/virt/rhevm/rhevm.py

1389729: virt-who incorrectly reports 'name' instead of 'hostname' for RHEV hosts.
This change makes virt-who report the actual hostname/IP address of the hypervisors, rather than the user-definable "hostname", which might not be an RFC-compliant hostname.

1389729: virt-who incorrectly reports 'name' instead of 'hostname'

---

virtwho/virt/esx/esx.py

The underlying connection will timeout in the event that there are no hosts to report on. In this case we should continue to try until there are hosts available.

1409984: Retry initial report retrieval on connection timeout

---

tests/test_config.py
virtwho/config.py

We'd like virt-who to continue to run when there are configurations that are invalid.
Should there be no configs that are valid virt-who will default to local libvirt.

1457101: Continue running despite malformed configs

---

virtwho/config.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1357761
* Check only usernames to be in latin1 encoding.
* Passwords can contain unicode characters.

1357761: Do not check passwords to be in latin1 encoding

---

tests/test_subscriptionmanager.py
virtwho/manager/subscriptionmanager/subscriptionmanager.py

We need to remove the use of the 'guestIds' attribute to match the update to CP 2.0 found here (https://github.com/candlepin/candlepin/pull/1517).
The use of the 'guestIds' attribute goes back a ways in virt-who, this will need to be fixed there as well.

1458674: Update use of result data to match the new async api

---

virtwho/virt/xen/xen.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1401420
* Manual pages already contains this information:
"hwuuid is applicable to esx and rhevm only."
* This bug is caused probably by copy pasting code from esx/rhevm.

1401420: xen supports only uuid/hostname as hypervisor_id

---

tests/test_satellite.py
tests/test_subscriptionmanager.py
tests/test_virtwho.py
virtwho/config.py
virtwho/main.py
virtwho/parser.py
virtwho/virt/virt.py

* Bug fix:
* https://bugzilla.redhat.com/show_bug.cgi?id=1461417
* https://bugzilla.redhat.com/show_bug.cgi?id=1404117
* Module argparse is used now, because optparse is marked
as obsolete and it does not provide required functionality
to fix this bug in elegant way.
* New subclass of Action was created. It is used for
checking consistency of command line options. When
virtualization backend is specified using e.g. --xen,
then --libvirt-username=admin cannot follow. There
should be --xen-username=admin.
* Command line arguments have to be in right order. It
means e.g. --libvirt has to be first and then
--libvirt-username=admin can follow.
* When --libvirt-username=admin is used without --libvirt,
then exception will be raised, because the argument
would not have any effect.
* Refactored …

1404117: Check parameter consistency and refactoring
